#!/usr/bin/env python3
"""Small OpenAI-compatible CPU server for the DeepEyes V2 judge model.

This is a resource-constrained fallback for colocated training runs where every
GPU is needed by the actor and rollout engines. Responses are generated by the
configured Hugging Face causal LM; the server never returns fixed judge text.
"""

from __future__ import annotations

import argparse
import os
import threading
import time
import uuid
from contextlib import asynccontextmanager
from typing import Any

import torch
import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse
from transformers import AutoModelForCausalLM, AutoTokenizer


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-path", required=True)
    parser.add_argument("--model-id", default="Qwen2.5-1.5B-Instruct")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=39001)
    parser.add_argument("--api-key", default="EMPTY")
    parser.add_argument("--max-input-tokens", type=int, default=8192)
    parser.add_argument("--max-new-tokens", type=int, default=256)
    parser.add_argument("--torch-dtype", choices=("float32", "bfloat16"), default="bfloat16")
    parser.add_argument("--threads", type=int, default=min(32, os.cpu_count() or 1))
    return parser.parse_args()


ARGS = parse_args()
torch.set_num_threads(ARGS.threads)
torch.set_num_interop_threads(max(1, min(4, ARGS.threads)))
DTYPE = torch.bfloat16 if ARGS.torch_dtype == "bfloat16" else torch.float32

TOKENIZER: Any = None
MODEL: Any = None
GENERATE_LOCK = threading.Lock()


@asynccontextmanager
async def lifespan(_: FastAPI):
    global MODEL, TOKENIZER
    TOKENIZER = AutoTokenizer.from_pretrained(ARGS.model_path, local_files_only=True)
    MODEL = AutoModelForCausalLM.from_pretrained(
        ARGS.model_path,
        dtype=DTYPE,
        device_map="cpu",
        local_files_only=True,
        low_cpu_mem_usage=True,
    )
    MODEL.eval()
    yield
    MODEL = None
    TOKENIZER = None


app = FastAPI(lifespan=lifespan)


def _authorize(request: Request) -> None:
    if ARGS.api_key == "EMPTY":
        return
    if request.headers.get("authorization") != f"Bearer {ARGS.api_key}":
        raise HTTPException(status_code=401, detail="invalid API key")


@app.get("/health")
async def health() -> dict[str, str]:
    if MODEL is None or TOKENIZER is None:
        raise HTTPException(status_code=503, detail="model is not loaded")
    return {"status": "ok", "device": "cpu", "model": ARGS.model_id}


@app.get("/v1/models")
async def models(request: Request) -> dict[str, Any]:
    _authorize(request)
    return {
        "object": "list",
        "data": [{"id": ARGS.model_id, "object": "model", "owned_by": "local"}],
    }


def _generate(messages: list[dict[str, Any]], temperature: float, requested_tokens: int) -> tuple[str, int, int]:
    prompt = TOKENIZER.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    encoded = TOKENIZER(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=ARGS.max_input_tokens,
    )
    input_tokens = int(encoded.input_ids.shape[-1])
    max_new_tokens = max(1, min(requested_tokens, ARGS.max_new_tokens))
    sampling = temperature > 0
    generation_args: dict[str, Any] = {
        "max_new_tokens": max_new_tokens,
        "do_sample": sampling,
        "pad_token_id": TOKENIZER.eos_token_id,
    }
    if sampling:
        generation_args["temperature"] = max(temperature, 1e-5)
        generation_args["top_p"] = 0.95
    with GENERATE_LOCK, torch.inference_mode():
        output = MODEL.generate(**encoded, **generation_args)
    generated = output[0, input_tokens:]
    text = TOKENIZER.decode(generated, skip_special_tokens=True).strip()
    return text, input_tokens, int(generated.numel())


@app.post("/v1/chat/completions")
async def chat_completions(request: Request) -> JSONResponse:
    _authorize(request)
    payload = await request.json()
    messages = payload.get("messages")
    if not isinstance(messages, list) or not messages:
        raise HTTPException(status_code=400, detail="messages must be a non-empty list")
    if payload.get("stream"):
        raise HTTPException(status_code=400, detail="streaming is not supported")
    try:
        text, prompt_tokens, completion_tokens = _generate(
            messages,
            float(payload.get("temperature", 0.3)),
            int(payload.get("max_tokens", ARGS.max_new_tokens)),
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"generation failed: {exc}") from exc
    return JSONResponse(
        {
            "id": f"chatcmpl-{uuid.uuid4().hex}",
            "object": "chat.completion",
            "created": int(time.time()),
            "model": ARGS.model_id,
            "choices": [
                {
                    "index": 0,
                    "message": {"role": "assistant", "content": text},
                    "finish_reason": "stop",
                }
            ],
            "usage": {
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
                "total_tokens": prompt_tokens + completion_tokens,
            },
        }
    )


if __name__ == "__main__":
    uvicorn.run(app, host=ARGS.host, port=ARGS.port, log_level="info")
